import { createWriteStream } from "fs";
import { finished } from "stream/promises";
import { formatSqlValue, quoteIdentifier } from "./escape.js";
import { columnToSqlType } from "./typeMap.js";

const INSERT_BATCH_ROWS = 500;

export class SqlFileWriter {
  /**
   * @param {string} outputPath
   */
  constructor(outputPath) {
    this.outputPath = outputPath;
    this.stream = createWriteStream(outputPath, { encoding: "utf8" });
    this._finished = finished(this.stream);
    this._closed = false;
  }

  /**
   * @param {string} chunk
   */
  _write(chunk) {
    return new Promise((resolve, reject) => {
      let settled = false;
      const settle = (fn, arg) => {
        if (settled) return;
        settled = true;
        fn(arg);
      };
      try {
        const ok = this.stream.write(chunk, "utf8", (err) => {
          if (err) settle(reject, err);
        });
        if (ok) settle(resolve);
        else this.stream.once("drain", () => settle(resolve));
      } catch (err) {
        settle(reject, err);
      }
    });
  }

  /**
   * @param {string} version
   * @param {string} absoluteSourcePath
   */
  async writePreamble(version, absoluteSourcePath) {
    const iso = new Date().toISOString();
    const lines = [
      `-- Generated by mdb-to-sql v${version}`,
      `-- Source: ${absoluteSourcePath}`,
      `-- Date  : ${iso}`,
      "",
    ];
    await this._write(lines.join("\n"));
  }

  /**
   * @param {string} tableName
   * @param {import('mdb-reader').Column[]} columns Ordenado conforme columnNames
   * @param {string[]} columnNames
   * @param {Generator<Record<string, import('mdb-reader').Value>[]>} rowChunkIterable
   */
  async writeTableSection(tableName, columns, columnNames, rowChunkIterable) {
    const qTable = quoteIdentifier(tableName);
    const header = [
      "-- --------------------------------------------------------",
      `-- Table: ${tableName}`,
      "-- --------------------------------------------------------",
      "",
    ].join("\n");

    const defs = columnNames
      .map((name, i) => {
        const col = columns[i];
        const sqlType = columnToSqlType(col);
        return `  ${quoteIdentifier(name)} ${sqlType}`;
      })
      .join(",\n");

    const create = [`CREATE TABLE IF NOT EXISTS ${qTable} (`, defs, ");", ""].join("\n");

    await this._write(header + create);

    for (const chunk of rowChunkIterable) {
      if (chunk.length === 0) continue;

      for (let i = 0; i < chunk.length; i += INSERT_BATCH_ROWS) {
        const slice = chunk.slice(i, i + INSERT_BATCH_ROWS);
        await this._writeBatchInsert(qTable, columns, columnNames, slice);
      }
    }

    await this._write("\n");
  }

  /**
   * @param {string} qTable
   * @param {import('mdb-reader').Column[]} columns
   * @param {string[]} columnNames
   * @param {Record<string, import('mdb-reader').Value>[]} rows
   */
  async _writeBatchInsert(qTable, columns, columnNames, rows) {
    const qCols = columnNames.map((n) => quoteIdentifier(n)).join(", ");
    const tuples = rows.map((row) => {
      const vals = columnNames.map((name, idx) =>
        formatSqlValue(columns[idx], row[name])
      );
      return `(${vals.join(", ")})`;
    });

    const body = [
      `INSERT INTO ${qTable} (${qCols}) VALUES`,
      "  " + tuples.join(",\n  ") + ";",
      "",
    ].join("\n");

    await this._write(body);
  }

  async close() {
    if (this._closed) {
      await this._finished;
      return;
    }
    this._closed = true;
    this.stream.end();
    await this._finished;
  }
}
